//Create Metros
MERGE (cavite:Metro {name: 'Cavite Island'})
MERGE (stGermain:Metro {name: 'St Germain'})
MERGE (pigalle:Metro {name: 'Pigalle'})
MERGE (montreal:Metro {name: 'Montreal'})
MERGE (quebec:Metro {name: 'Quebec'})
MERGE (fortTilden:Metro {name: 'Fort Tilden'})
MERGE (intramuros:Metro {name: 'Intramuros'})
MERGE (chinaTown:Metro {name: 'China Town'})
MERGE (stDomingo:Metro {name: 'St Domingo'})
MERGE (coneyIsland:Metro {name: 'Coney Island'})
MERGE (brooklyn:Metro {name: 'Brooklyn'})
MERGE (uptown:Metro {name: 'Uptown'})
MERGE (cardShark:Metro {name: 'Card Shark'})
MERGE (divisoria:Metro {name: 'Divisoria'})
MERGE (ermita:Metro {name: 'Ermita'})
MERGE (nyc:Metro {name: 'NYC'})
MERGE (staIsabel:Metro {name: 'Sta Isabel'})
MERGE (theRuins:Metro {name: 'The Ruins'})
MERGE (phoenix:Metro {name: 'Phoenix'})
MERGE (bastille:Metro {name: 'Bastille'})
MERGE (puertoDelPostigo:Metro {name: 'Puerto del Postigo'})
MERGE (redLight:Metro {name: 'Red Light'})
MERGE (hotelStPaul:Metro {name: 'Hotel St Paul'})

//Create Routes
MERGE (cavite)-[:HAS_ROUTE {travelTime: 2.5}]-(intramuros)
MERGE (cavite)-[:HAS_ROUTE {travelTime: 3}]-(fortTilden)
MERGE (stGermain)-[:HAS_ROUTE {travelTime: 9}]-(intramuros)
MERGE (stGermain)-[:HAS_ROUTE {travelTime: 5.6}]-(chinaTown)
MERGE (pigalle)-[:HAS_ROUTE {travelTime: 6}]-(chinaTown)
MERGE (pigalle)-[:HAS_ROUTE {travelTime: 4}]-(montreal)
MERGE (pigalle)-[:HAS_ROUTE {travelTime: 8.5}]-(nyc)
MERGE (montreal)-[:HAS_ROUTE {travelTime: 3}]-(quebec)
MERGE (fortTilden)-[:HAS_ROUTE {travelTime: 13}]-(brooklyn)
MERGE (coneyIsland)-[:HAS_ROUTE {travelTime: 1.5}]-(brooklyn)
MERGE (brooklyn)-[:HAS_ROUTE {travelTime: 2.5}]-(uptown)
MERGE (brooklyn)-[:HAS_ROUTE {travelTime: 5}]-(theRuins)
MERGE (uptown)-[:HAS_ROUTE {travelTime: 5}]-(intramuros)
MERGE (intramuros)-[:HAS_ROUTE {travelTime: 11}]-(chinaTown)
MERGE (intramuros)-[:HAS_ROUTE {travelTime: 16.5}]-(bastille)
MERGE (chinaTown)-[:HAS_ROUTE {travelTime: 7.5}]-(divisoria)
MERGE (chinaTown)-[:HAS_ROUTE {travelTime: 4.5}]-(ermita)
MERGE (chinaTown)-[:HAS_ROUTE {travelTime: 12.5}]-(nyc)
MERGE (theRuins)-[:HAS_ROUTE {travelTime: 4}]-(cardShark)
MERGE (theRuins)-[:HAS_ROUTE {travelTime: 5.5}]-(phoenix)
MERGE (theRuins)-[:HAS_ROUTE {travelTime: 2.5}]-(redLight)
MERGE (cardShark)-[:HAS_ROUTE {travelTime: 4.5}]-(phoenix)
MERGE (divisoria)-[:HAS_ROUTE {travelTime: 6.5}]-(bastille)
MERGE (ermita)-[:HAS_ROUTE {travelTime: 9}]-(puertoDelPostigo)
MERGE (nyc)-[:HAS_ROUTE {travelTime: 10.5}]-(puertoDelPostigo)
MERGE (nyc)-[:HAS_ROUTE {travelTime: 5}]-(stDomingo)
MERGE (nyc)-[:HAS_ROUTE {travelTime: 2}]-(staIsabel)
MERGE (phoenix)-[:HAS_ROUTE {travelTime: 3.5}]-(redLight)
MERGE (phoenix)-[:HAS_ROUTE {travelTime: 10}]-(bastille)
MERGE (bastille)-[:HAS_ROUTE {travelTime: 6.5}]-(hotelStPaul)
MERGE (bastille)-[:HAS_ROUTE {travelTime: 6}]-(puertoDelPostigo)
MERGE (puertoDelPostigo)-[:HAS_ROUTE {travelTime: 3}]-(staIsabel)